version: '3.4'

services:
  spaceshooter:
    image: notmatthias/highscore-backend
    build:
      context: .
      dockerfile: SpaceShooter/Dockerfile

  frontend:
    image: notmatthias/highscore-frontend
    build: ../client
    depends_on:
      - spaceshooter